using UnityEngine;
using System.Collections.Generic;

public class TerrainMaster : MonoBehaviour
{
    public float targetDensity;
    public int bailOutLimit; 
    public int x_lim;
    public int y_lim; 
    public int z_lim;
    public float scaleFactor;
    public GameObject crystallineComponent;
    public int finalNumberMapSegements;
    public float SegmentRadiusFudgeFactor = 0.6f;

    [System.NonSerialized] public int numMapSegments = 0;
    [System.NonSerialized] List<GameObject> mapSegments = new List<GameObject>();
    
    private float effectiveSegmentRadius;

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        effectiveSegmentRadius = (x_lim + y_lim + z_lim)/3/2;

        // createMapSegment();
        // for (int i=1; i<finalNumberMapSegements; i++){
        //     GameObject newestSegment = createMapSegment();
        //     GameObject previousSegment = mapSegments[i-1];
        //     Vector3 toNewSegmentVector = new Vector3(2*scaleFactor*SegmentRadiusFudgeFactor*effectiveSegmentRadius, 0f, 0f);
        //     newestSegment.transform.position = previousSegment.transform.position + toNewSegmentVector;
        // }
        
        GameObject masterMapParent = new GameObject("MasterMapParent"); //empty parent

        //new bounds for master map
        int master_x_lim = 10;
        int master_y_lim = 10;
        int master_z_lim = 10;

        //creating dla controller
        DLA masterDLA = new DLA(master_x_lim, master_y_lim, master_z_lim);
        masterDLA.GenerateDLA(targetDensity, bailOutLimit*2);

        List<(int,int, int)> locations = masterDLA.getLocations(); // the list of locations
        
        //instantiating all the objects for generated by the DLA & scaling them
        for (int i=0; i<locations.Count; i++){
            Vector3 targetPos = new Vector3((float)locations[i].Item1, (float)locations[i].Item2, (float)locations[i].Item3);
            targetPos = targetPos - new Vector3(master_x_lim/2f, master_y_lim/2f, master_z_lim/2f); // here we have to make the center of the DLA object be (0,0,0)
            GameObject nextMapSegment = createMapSegment();
            nextMapSegment.transform.position = targetPos*scaleFactor*effectiveSegmentRadius;
            nextMapSegment.transform.rotation = Quaternion.identity;

            nextMapSegment.transform.localScale = nextMapSegment.transform.localScale*scaleFactor;
            
            nextMapSegment.transform.SetParent(masterMapParent.transform);
        }
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    //creates a map segment and parents all objects to a single empty
    GameObject createMapSegment(){  
        numMapSegments++;
        GameObject segmentParent = new GameObject("MapSegment"+numMapSegments);

        DLA masterDLA = new DLA(x_lim, y_lim, z_lim);

        masterDLA.GenerateDLA(targetDensity, bailOutLimit);

        List<(int,int, int)> locations = masterDLA.getLocations();
        //instantiating all the objects for generated by the DLA & scaling them
        for (int i=0; i<locations.Count; i++){
            Vector3 targetPos = new Vector3((float)locations[i].Item1, (float)locations[i].Item2, (float)locations[i].Item3);
            targetPos = targetPos - new Vector3(x_lim/2, y_lim/2, z_lim/2); // here we have to make the center of the DLA object be (0,0,0)
            GameObject newComponent = Instantiate(crystallineComponent, targetPos*scaleFactor, Quaternion.identity);
            newComponent.transform.localScale = newComponent.transform.localScale*scaleFactor;
            newComponent.SetActive(true);
            newComponent.transform.SetParent(segmentParent.transform);
        }

        mapSegments.Add(segmentParent);
        return segmentParent;
    }
}
