using UnityEngine;
using System.Collections.Generic;

public class TerrainMaster : MonoBehaviour
{
    [Header("DLA Settings")]
    public float targetDensity;
    public int bailOutLimit; 
    public int x_lim;
    public int y_lim; 
    public int z_lim;

    [Header("Map Settings")]
    public float scaleFactor;
    public GameObject crystallineComponent;
    public int finalNumberMapSegements;
    public float segmentRadiusFudgeFactor = 0.6f;

    [Header("Ore Settings")]
    public GameObject oreObject;
    public float oreSpawnProbability;

    [System.NonSerialized] public int numMapSegments = 0;
    [System.NonSerialized] List<GameObject> mapSegments = new List<GameObject>();
    
    private float effectiveSegmentRadius;

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        effectiveSegmentRadius = (x_lim + y_lim + z_lim)/3/2;
        
        GameObject masterMapParent = new GameObject("MasterMapParent"); //empty parent

        //new bounds for master map
        int master_x_lim = 10;
        int master_y_lim = 10;
        int master_z_lim = 10;

        //creating dla controller
        DLA masterDLA = new DLA(master_x_lim, master_y_lim, master_z_lim);
        masterDLA.GenerateDLA(targetDensity, bailOutLimit*2);

        List<(int,int, int)> locations = masterDLA.getLocations(); // the list of locations
        
        //instantiating all the objects for generated by the DLA & scaling them
        for (int i=0; i<locations.Count; i++){
            Vector3 targetPos = new Vector3((float)locations[i].Item1, (float)locations[i].Item2, (float)locations[i].Item3);
            targetPos = targetPos - new Vector3(master_x_lim/2f, master_y_lim/2f, master_z_lim/2f); // here we have to make the center of the DLA object be (0,0,0)
            
            GameObject nextMapSegment = createMapSegment();
            nextMapSegment.transform.SetParent(masterMapParent.transform, false);
            nextMapSegment.transform.localPosition = targetPos*scaleFactor*effectiveSegmentRadius*segmentRadiusFudgeFactor;
            nextMapSegment.transform.localRotation = Quaternion.identity;
        }
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    //creates a map segment and parents all objects to a single empty
    GameObject createMapSegment(){  
        numMapSegments++;
        GameObject segmentParent = new GameObject("MapSegment"+numMapSegments);

        DLA masterDLA = new DLA(x_lim, y_lim, z_lim);

        masterDLA.GenerateDLA(targetDensity, bailOutLimit);

        List<(int,int, int)> locations = masterDLA.getLocations();
        //instantiating all the objects for generated by the DLA & scaling them
        for (int i=0; i<locations.Count; i++){
            Vector3 targetPos = new Vector3((float)locations[i].Item1, (float)locations[i].Item2, (float)locations[i].Item3);
            targetPos = targetPos - new Vector3(x_lim/2, y_lim/2, z_lim/2); // here we have to make the center of the DLA object be (0,0,0)

            GameObject newComponent;
            if (Random.value >= oreSpawnProbability){ //normal block
                newComponent = Instantiate(crystallineComponent, segmentParent.transform);
            }else{ //ore block
                newComponent = Instantiate(oreObject, segmentParent.transform);
            }
            
            newComponent.transform.localPosition = targetPos * scaleFactor;
            newComponent.transform.localRotation = Quaternion.identity;
            newComponent.transform.localScale = Vector3.one * scaleFactor;
            newComponent.SetActive(true);

            //now we determine if we are going to spawn an ore on this block

            //now we determine if we are going to place a gnome spawning object on this block


        }

        mapSegments.Add(segmentParent);
        return segmentParent;
    }
}
